version: '3.1'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_USER_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}

  webserver:
    build:
      context: .
    restart: always
    ports:
      - ${WEB_SERVER_PORT}:80
    volumes:
      - $PWD/:/var/www/html/
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
